# Generated by Django 4.1.1 on 2025-01-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('Ciencia Ficción', 'Ciencia Ficción'), ('Terror', 'Terror'), ('Suspenso', 'Suspenso'), ('Romantica', 'Romantica'), ('Comedia', 'Comedia')], max_length=50),
        ),
    ]
