# Generated by Django 4.1.1 on 2025-01-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_pelicula_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('Ciencia Ficción', 'Ciencia Ficción'), ('Terror', 'Terror'), ('Suspenso', 'Suspenso'), ('Romantica', 'Romántica'), ('Comedia', 'Comedia'), ('Acción', 'Acción'), ('Drama', 'Drama'), ('Crimen', 'Crimen'), ('Animación', 'Animación')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='precio_arriendo',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('completada', 'Completada'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('arriendo', 'Arriendo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(max_length=255),
        ),
    ]
